# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- script: | 
    sudo apt-get update -y
    sudo apt-get install build-essential -y
    sudo apt install python3-pip -y
    sudo apt-get install cucumber -y
    sudo pip3 install cmake 
    sudo pip3 install conan
    conan profile new default --detect
    conan profile update settings.compiler.libcxx=libstdc++11 default
    conan create ./conanfile/cucumber-cpp/conanfile.py cucumber-cpp/0.5@cwt/stable --build missing
    conan install . -if build --build missing
    cmake -S . -B ./build 
    cmake --build ./build
    ./build/bin/cucumber_example  &
    cucumber ./features

  displayName: 'build and run'