# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- script: | 
    sudo apt-get update
    sudo apt-get install build-essential
    sudo apt-get install libboost-all-dev
    sudo apt-get install libgtest-dev
    sudo apt install cucumber
    git clone https://github.com/cucumber/cucumber-cpp
    sudo cmake -S ./cucumber-cpp -B ./cucumber-cpp/build
    sudo cmake --build ./cucumber-cpp/build
    sudo cmake --install ./cucumber-cpp/build
    sudo cmake -S ./ -B ./build -DCUCUMBER_ROOT=/usr/local
    sudo cmake --build ./build
    pwd
    ./build/bin/cucumer_example  &
    cd ./src/cucumber
    cucumber ./features/example.feature
    

  displayName: 'build and run'